# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8ab9e9842142bf11c73acf8f197317d7ab7e314e0fe4e1873510497d28083c242ddf58d1b6cd470aaf6620bc0064e4d721e0af3f8d506fc25f0e32e75a8b128

test:
  secret_key_base: 76c1245bb0b61f86ad7955269d8bd215c7734ffd23d33c7e12e70583782a8e4ca0db3ba861e4cb99e88f14ec6d7ae2730f7a1cce88b1efe92353a92011de4ae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
